name: CI/CD Workflow for Evenements

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
    
    - name: Login to Railway
      run: railway login --token ${{ secrets.RAILWAY_TOKEN }}
    
    - name: Link to Railway Project
      run: |
        railway link ${{ secrets.RAILWAY_PROJECT }}
    
    - name: Deploy to Railway
      run: |
        railway up --detach \
          -e MYSQLHOST=${{ secrets.MYSQLHOST }} \
          -e MYSQLPORT=${{ secrets.MYSQLPORT }} \
          -e MYSQLDATABASE=${{ secrets.MYSQLDATABASE }} \
          -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}